/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i struct_marshallers_p.h -a deviceeventcontroller_adaptor.h: dbusxml/DeviceEventController.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DEVICEEVENTCONTROLLER_ADAPTOR_H
#define DEVICEEVENTCONTROLLER_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "struct_marshallers_p.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.a11y.atspi.DeviceEventController
 */
class DeviceEventControllerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.a11y.atspi.DeviceEventController")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.a11y.atspi.DeviceEventController\">\n"
"    <method name=\"NotifyListenersSync\">\n"
"      <arg direction=\"in\" type=\"(uinnisb)\" name=\"event\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <annotation value=\"QSpiDeviceEvent\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"NotifyListenersAsync\">\n"
"      <arg direction=\"in\" type=\"(uinnisb)\" name=\"event\"/>\n"
"      <annotation value=\"QSpiDeviceEvent\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DeviceEventControllerAdaptor(QObject *parent);
    virtual ~DeviceEventControllerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void NotifyListenersAsync(const QSpiDeviceEvent &event);
    bool NotifyListenersSync(const QSpiDeviceEvent &event);
Q_SIGNALS: // SIGNALS
};

#endif
