# Dataset Creator Config
num_cameras: 5
raw_data_type: images
data_paths:
- /home/lambda/Documents/Recordings/Recording_29_Objects/Recording_13082020-110615_Cam1.avi
- /home/lambda/Documents/Recordings/Recording_29_Objects/Recording_13082020-110615_Cam2.avi
- /home/lambda/Documents/Recordings/Recording_29_Objects/Recording_13082020-110615_Cam3.avi
- /home/lambda/Documents/Recordings/Recording_29_Objects/Recording_13082020-110615_Cam4.avi
- /home/lambda/Documents/Recordings/Recording_29_Objects/Recording_13082020-110615_Cam5.avi
make_copy_of_images: False
image_savepath: Data/29_Objects/Imgs_Objects/Object_0

#AnnotationConfig
scorer: Cara
entities:
- Right Hand
- Left Hand

bodyparts:
- Pinky_T
- Pinky_D
- Pinky_M
- Pinky_P
- Ring_T
- Ring_D
- Ring_M
- Ring_P
- Middle_T
- Middle_D
- Middle_M
- Middle_P
- Index_T
- Index_D
- Index_M
- Index_P
- Thumb_T
- Thumb_D
- Thumb_M
- Thumb_P
- Palm
- Wrist_U
- Wrist_R
- Elbow_U
- Elbow_R
- Shoulder

#Reprojection Config
enable_reprojection: True
reprojection_min_views: 2
#Order must be the same as recording data_paths, primary will be inserted at primary_index (starts at 0)
primary_index: 0
camera_calibration_locations:
- Camera_Calib_Parameters/CalibParams_1000_T_1180_Table/Camera_Pair_T_RF
- Camera_Calib_Parameters/CalibParams_1000_T_1180_Table/Camera_Pair_T_LF
- Camera_Calib_Parameters/CalibParams_1000_T_1180_Table/Camera_Pair_T_RB
- Camera_Calib_Parameters/CalibParams_1000_T_1180_Table/Camera_Pair_T_LB
