QT_PLUGIN.ibusplatforminputcontextplugin.TYPE = platforminputcontexts
QT_PLUGIN.ibusplatforminputcontextplugin.EXTENDS = -
QT_PLUGIN.ibusplatforminputcontextplugin.DEPENDS = core gui dbus gui_private xkbcommon_support_private
QT_PLUGIN.ibusplatforminputcontextplugin.CLASS_NAME = QIbusPlatformInputContextPlugin
QT_PLUGINS += ibusplatforminputcontextplugin
