QT_CPU_FEATURES.x86_64 = cx16 mmx sse sse2 sse3
QT.global_private.enabled_features = sse2 alloca_malloc_h alloca dbus gc_binaries gui network sql system-zlib testlib widgets xml
QT.global_private.disabled_features = alloca_h android-style-assets avx2 private_tests dbus-linked dlopen intelcet libudev posix_fallocate reduce_exports reduce_relocations release_tools relocatable stack-protector-strong zstd
QT_COORD_TYPE = double
QMAKE_LIBS_ZLIB = -lz
CONFIG -= precompile_header
CONFIG += sse2 aesni sse3 ssse3 sse4_1 sse4_2 compile_examples largefile optimize_size rdrnd shani x86SimdAlways
QT_BUILD_PARTS += libs
QT_HOST_CFLAGS_DBUS += 
