QT_PLUGIN.composeplatforminputcontextplugin.TYPE = platforminputcontexts
QT_PLUGIN.composeplatforminputcontextplugin.EXTENDS = -
QT_PLUGIN.composeplatforminputcontextplugin.DEPENDS = core gui core_private gui_private
QT_PLUGIN.composeplatforminputcontextplugin.CLASS_NAME = QComposePlatformInputContextPlugin
QT_PLUGINS += composeplatforminputcontextplugin
