QT_PLUGIN.qtgeoservices_itemsoverlay.TYPE = geoservices
QT_PLUGIN.qtgeoservices_itemsoverlay.EXTENDS =
QT_PLUGIN.qtgeoservices_itemsoverlay.DEPENDS = core gui location_private positioning_private
QT_PLUGIN.qtgeoservices_itemsoverlay.CLASS_NAME = QGeoServiceProviderFactoryItemsOverlay
QT_PLUGINS += qtgeoservices_itemsoverlay
